version=1.0.1
group=net.le0nia.inconsistentize
java_version=21

minecraft_version=1.21.10
mod_name=Inconsistentize
mod_author=Le0nia
mod_id=inconsistentize
license=MIT
credits=
description=Makes it so that item entities are picked up by a random player in the area, rather than the vanilla pickup behaviour - the first player who joined the server picking up the item.
minecraft_version_range=[1.21.10, 1.22)
neo_form_version=1.21.10-20251010.172816
parchment_minecraft=1.21.9
parchment_version=2025.10.05

fabric_version=0.135.0+1.21.10
fabric_loader_version=0.17.3

forge_version=60.0.3
forge_loader_version_range=[60,)

neoforge_version=21.10.8-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
